### ISSUE TITLE
Copyright PlanetaryPy

### ISSUE THREAD

**Issue by godber** [planetarypy/pvl#2]
I noticed that you have assigned copyright to planetarypy.  If this is inadvertent, please send a PR to reassign the copyright to yourself.  If you do want to do that, then we should decide what PlantaryPy is ... appoint a board or something, so its a better defined entity.

**Comment by godber** [comment]
Also I have fixed your access to this repository.  I didn't realize that I needed to assign groups to repos as well.

**Comment by wtolson** [comment]
Thanks Austin. I'm going to follow [Astropy's](https://github.com/astropy/astropy/blob/master/licenses/LICENSE.rst) and [urllib3's](https://github.com/shazow/urllib3/blob/master/LICENSE.txt) example on this one and make sure it states copyright is assigned to the contributers. PR incoming.

**Comment by godber** [comment]
Good decision, Astropy is very well organized and thought out and as I've said in person, they will serve as my model for many things.
