### ISSUE TITLE
Proposal: Add pathlib functionality

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/pvl#31]
I'm not sure if you want to keep Python2 compatibility, but in Python3 `pathlib` is part of the standard library, in Py2 it would create a dependency, but it's usually included now in standard envs like (ana/mini)conda in the form of `pathlib2`.

**Comment by rbeyer** [comment]
Done as part of #38, this issue can be closed.

**Comment by AndrewAnnex** [comment]
@rbeyer, did you mean to close this issue yourself? if not I did so
