### ISSUE TITLE
fix readthedocs config

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/pvl#43]
i just added autoprogram.

good thing is, after Ross' merge, the doc building process started automatically, so that's working as well.
Now just need to work on the config until it works.

**Comment by rbeyer** [comment]
No, I've been hitting the RTD button.  To set up webhooks, you need to do that Git-side, and I don't have the priviledges in planetarypy/pvl to see 'Webhooks' under 'Settings' : https://docs.readthedocs.io/en/stable/webhooks.html

**Comment by michaelaye** [comment]
Weird, i thought i saw the maintainer group has full access? build completed now, btw.

**Comment by michaelaye** [comment]
text starts with:

"Support for Python 2, 3 and pypi."

Guess we remove Python 2 support? Or is pvl still supporting that?

**Comment by rbeyer** [comment]
I do not understand GitHub Teams and permissions.  If you can see the "Webhooks" thing, then you can fix it.

If you're seeing ""Support for Python 2, 3 and pypi." that's not the latest docs.  It seems like the latest has passed building, but maybe isn't showing yet?  Maybe its a cache thing?

**Comment by rbeyer** [comment]
Okay, now I'm seeing the new docs.  Yay!

**Comment by michaelaye** [comment]
wow, indeed. i had to Shift-Reload! Now seeing new ones as well. I resynced the webhook, let's see if that worked. Closing this for now.

**Comment by michaelaye** [comment]
actually, the resync added a new webhook to the repo's settings, so we should be golden now.
