### ISSUE TITLE
Create new pypi build

### ISSUE THREAD

**Issue by michaelaye** [planetarypy/pvl#45]
We need to establish a best approach to push new builds to Pypi.

**Comment by rbeyer** [comment]
If we can set up the system folks were talking about today whereby tagging a release on the GitHub Repo triggers a build and a push to pypi, that would be pretty slick.

**Comment by michaelaye** [comment]
Yes. IIIUC it still required an Org access token so how do we get that if the Pypi account is linked to @wtolson ? Maybe that token could be shared with us maintainers? As it’s encoded it would be like sharing the password.

**Comment by michaelaye** [comment]
Would NOT be like sharing passwords

**Comment by AndrewAnnex** [comment]
You can look at spiceypy for the workflow for the way i publish to pypi.

I want to see if there is an existing best practices guide for doing this but my guess would be to:

 someone who is willing to make a pypi account for the org and to hold on to the password for now. The password could be safeguarded using a password manager like last pass that allows passwords to be shared, and could be trusted to two folks for redundancy. I wonder if there are existing services for managing a shared secret...

Then the current pypi maintainers would add this new pypi org as a maintainer. The password gets shared by encrypting it via the CI service, and would then get committed to the repository 

-Andrew Annex

**Comment by godber** [comment]
With @wtolson's approval I will grant @michaelaye Owner access to pvl on pypi.  I've confirmed that I can still login.  I can ping @wtolson out of band if it becomes necessary.

**Comment by godber** [comment]
@michaelaye I've granted Owner role to your PyPI account for `pvl`

https://pypi.org/user/michaelaye/

**Comment by godber** [comment]
I received out of band approval from wtolson.

**Comment by rbeyer** [comment]
Thanks @godber and @wtolson for helping us move `pvl` forward.

**Comment by rbeyer** [comment]
@michaelaye so now that you have the pypi power, you can push new versions to pypi.  

That's step 0.

Then probably doing what @AndrewAnnex is talking about and create a 'planetarypy' pypi account, and then getting it all set up with Travis, etc.

**Comment by rbeyer** [comment]
Alright, we've got version 1.0.0 merged, the tests pass, so we're ready to push this version to pypi.  I think that means @michaelaye needs to do it (and that should then cascade to conda).

**Comment by AndrewAnnex** [comment]
I think after this release we should add the GitHub action for publishing to pypi. It is fairly trivial once we set up a token that is a secret associated with the repository. However pypi credentials are still needed to setup the token 

-Andrew Annex

**Comment by rbeyer** [comment]
Michael pushed the new PyPI build, but this Issue is really about best practices, which we still need to do.

**Comment by rbeyer** [comment]
I *think* this is done.  We now have a GitHub Action that publishes to PyPI when a GitHub release is minted.  There was a minor syntax error in the HISTORY.rst that prevented that Action from completing with the creation of Release 1.3.0.  So I want to wait until our next release, to ensure that this does really happen smoothly, and then we can close.

**Comment by rbeyer** [comment]
Confirmed that this is now all working correctly.  When you mint a Release via GitHub, the action properly fires, and uploads to PyPI.
