### ISSUE TITLE
Add PDS3 label encoding support

### ISSUE THREAD

**Issue by godber** [planetarypy/pvl#8]
The `encode.LabelEncoder` class currently encodes to Isis CubeFile type headers.  We need a way to encode to PDS3 Labels.

**Comment by wtolson** [comment]
I think we should make `LabelEncoder` default to the official pvl style which I believe is the same style as PDS3 labels. Then create a separate `CubeLabelEncoder` subclass which preserves the CubeFile style.

**Comment by wtolson** [comment]
Added in latest release.
